INSERT INTO GENEROS(NAME) VALUES('Acción');
INSERT INTO GENEROS(NAME) VALUES('Amor');
INSERT INTO GENEROS(NAME) VALUES('Comedia');
INSERT INTO GENEROS(NAME) VALUES('Drama');
INSERT INTO GENEROS(NAME) VALUES('Fantasía');
INSERT INTO GENEROS(NAME) VALUES('Independiente');
INSERT INTO GENEROS(NAME) VALUES('Mexicana');
INSERT INTO GENEROS(NAME) VALUES('Suspenso');
INSERT INTO GENEROS(NAME) VALUES('Terror');
INSERT INTO GENEROS(NAME) VALUES('Western');

INSERT INTO ACTORES(NAME, URL_IMAGEN) VALUES('Joaquín Cosio', 'https://images.app.goo.gl/stetujEUiphfGjo26');
INSERT INTO ACTORES(NAME, URL_IMAGEN) VALUES('Steve Carrel', 'https://images.app.goo.gl/WTcu1o8C3HyLD6TXA');
